### ISSUE TITLE
Sorting by column seems to be broken for some columns

### ISSUE THREAD

**Issue by m6sec** [hvqzao/burp-flow#1]
Tested with flow 1.03 and flow 1.04:

When in the flow tab, one can click all columns header to sort the results. However it looks like some columns such as "Length", "Parameters" and "Count" do not seem to be sortable at all. Other headers like "MIME" seems to only work some times (e.g. when one has sorted it by another column beforehand)

**Comment by hvqzao** [comment]
I think it should (mostly) work now (I didn't notice issues on MIME sorting)
Commit: https://github.com/hvqzao/burp-flow/commit/3f7f0b4dd39d4dcd7b92aa786d6f02f85192c618
Binary release: 1.05

**Comment by hvqzao** [comment]
Solved
