### ISSUE TITLE
Can you add to filter by file extension...

### ISSUE THREAD

**Issue by teslatheg0d** [hvqzao/burp-flow#15]
Can you add a filter by file extension like this 
![image](https://user-images.githubusercontent.com/61558155/104111773-5672a900-530c-11eb-949d-4abbe110afc8.png)

**Comment by hvqzao** [comment]
No, please use Target | Scope | [x] Use advanced scope control
there you can add e.g. ^/.*\.(js|css|gif|png|jpg|jpeg|ico|svg|woff|woff2|eot|ttf)(;|\?|$)
If you don't want to memorize this, you can use my other extension:
https://github.com/hvqzao/burp-wildcard/releases/tag/1.08
(Exclude common static files)
Once you click it, you can edit excludes on Scope tab
In both Proxy | History and Flow you can check [x] Show only in-scope

Alternatively you can use Filter feature in Flow and regex feature there
