### ISSUE TITLE
Problems with the search interface in high resolution

### ISSUE THREAD

**Issue by ewilded** [hvqzao/burp-flow#2]
I noticed that when using Flow in high resolution (like 4k), the 'search' filter interface elements overlap each other, rendering it useless. Manually resizing the popped-up area does not update element alignment and therefore does not help.
Please see the screenshot.
![flow](https://cloud.githubusercontent.com/assets/1158719/19031924/393fe808-8957-11e6-94a6-c83aabcfae4c.png)

**Comment by hvqzao** [comment]
Oh. I'm afraid I will not be able to prepare quick fix for retina displays at the moment. If you have some spare time, you can fetch "dev" branch I've just prepared and try to hack on your own. I hope to be able to resolve the issue in a future. Anyways - great thanks for your feedback!

**Comment by hvqzao** [comment]
Could you show me a screenshot of how layout looks for build attached below?

[flow.zip](https://github.com/hvqzao/burp-flow/files/528161/flow.zip)
