### ISSUE TITLE
Very long reflection tooltips hang BurpSuite completely (kali linux 2019.1)

### ISSUE THREAD

**Issue by manuelbua** [hvqzao/burp-flow#6]
Hi, i noticed that very long reflection tooltips are prone to hang the whole BurpSuite interface completely and there is no way to recover anything when this happens, so `kill -9` is the only way to terminate it.
This ofter happens when using the ParamMiner extension, where lot of reflections can be triggered at once.

Is there a way to disable them?

**Comment by hvqzao** [comment]
Hi, this is adressed in newest release. Number of reflections can be customized (top right options icon). It is also truncated by default and limited to 10 entries.
See https://github.com/hvqzao/burp-flow/releases/tag/1.24
I'll inform PortSwigger to update it in BApps Store.

**Comment by manuelbua** [comment]
Hi @hvqzao thank you much for addressing this!
